import {
  BadgeAlert,
  BarChart3,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Calendar,
  CalendarRange,
  ClipboardCheck,
  Clock,
  FileSignature,
  FileText,
  Folder,
  GraduationCap,
  Home,
  Inbox,
  LayoutDashboard,
  LifeBuoy,
  ListChecks,
  Megaphone,
  MessageSquare,
  Receipt,
  Settings,
  Shield,
  Smartphone,
  Target,
  UserPlus,
  Users,
  Wallet,
  Bell,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "./types";

const ICONS: Record<IconName, LucideIcon> = {
  users: Users,
  inbox: Inbox,
  "file-text": FileText,
  shield: Shield,
  "layout-dashboard": LayoutDashboard,
  bell: Bell,
  smartphone: Smartphone,
  settings: Settings,
  clock: Clock,
  calendar: Calendar,
  briefcase: Briefcase,
  "clipboard-check": ClipboardCheck,
  "badge-alert": BadgeAlert,
  wallet: Wallet,
  bus: Bus,
  receipt: Receipt,
  "graduation-cap": GraduationCap,
  target: Target,
  building: Building2,
  megaphone: Megaphone,
  "calendar-range": CalendarRange,
  "list-checks": ListChecks,
  "bar-chart": BarChart3,
  "file-signature": FileSignature,
  "user-plus": UserPlus,
  folder: Folder,
  "book-open": BookOpen,
  "message-square": MessageSquare,
  home: Home,
  "life-buoy": LifeBuoy,
};

export function ModuleIcon({ name, className }: { name: IconName; className?: string }) {
  const Icon = ICONS[name];
  return <Icon className={className} aria-hidden />;
}
