/**
 * Admin pages that exist so far. Sidebar links, "Jump to" and checklist
 * items only appear/link once their page is built, so nobody lands on a
 * "page not found". Each build phase adds its pages here.
 */
export const AVAILABLE_ROUTES = new Set<string>([
  "/app",
  "/app/requests",
  "/app/people",
  "/app/people/new",
  "/app/people/org-chart",
  "/app/letters",
  "/app/news",
  "/app/notifications",
  "/app/account",
  "/app/workspace/tools",
  "/app/workspace/people",
  "/app/workspace/requests",
  "/app/workspace/company",
  "/app/workspace/notifications",
  "/app/workspace/activity",
  "/app/workspace/data",
  "/app/workspace/support",
  "/app/workspace/tools/employees",
  "/app/workspace/tools/leave",
  "/app/workspace/tools/attendance",
  "/app/workspace/tools/payroll",
  "/app/workspace/tools/claims",
  "/app/workspace/tools/performance",
  "/help",
  "/staff",
  "/staff/requests",
  "/staff/letters",
  "/staff/files",
  "/staff/directory",
  "/staff/me",
  "/staff/notifications",
  "/staff/time",
  "/staff/time-off",
  "/app/time",
  "/app/time/roster",
  "/app/time/timesheets",
  "/app/time-off",
  "/app/time-off/calendar",
  "/app/payroll",
  "/app/claims",
  "/app/hiring",
  "/app/hiring/new",
  "/app/joiners-leavers",
  "/app/joiners-leavers/checklists",
  "/app/permits",
  "/staff/tasks",
  "/app/training",
  "/app/training/new",
  "/app/training/paid",
  "/app/reviews",
  "/app/reviews/goals",
  "/app/reviews/surveys",
  "/staff/courses",
  "/staff/goals",
  "/staff/reviews",
  "/staff/surveys",
  "/staff/pay",
  "/staff/claims",
]);

export function isRouteAvailable(href: string): boolean {
  return AVAILABLE_ROUTES.has(href.split("?")[0]);
}
